### PR TITLE
Add directions to see presentation attachments

### PR DESCRIPTION
**Pull request by doctor-gonzo**
Ananya sent me a big document with lots of details about I+R events. If anyone knows how to add markdown links to JSON that would be great, then I could add the whole document Ananya sent me. 

I am looking at stuff like this: https://forum.middlemanapp.com/t/rendering-markdown-from-json-data-file/1845/3

but would appreciate any leads and would be happy to try to do the coding myself if you have any tips that would help get me started

### CODE REVIEW

**Comment by doctor-gonzo** [comment]
there is an HTML link in there that I am assuming that it will work with the json, but I could be wrong

**Comment by gigamesh** [comment]
...sorry I think I misunderstood. Is the document you have already in markdown format? JSON.stringify() will create JSON out of any JavaScript object, so that might be what you're looking for (ex: convert the document to key/value pairs, then pass to JSON.stringify()). I think I'd have to see the document to understand better.

**Comment by doctor-gonzo** [comment]
the link is just to a pdf that Ananya wanted displayed on the website, it can be seen here:

https://firebasestorage.googleapis.com/v0/b/hoverboard-site-prod.appspot.com/o/Presenations%20%26%20Abstracts%20%26%20Session%20Descriptions%2FI%2BR%2FOverall%20Agenda%20Description.pdf?alt=media&token=de26cc28-1295-4aef-87ad-8767dc96be96

I am just trying to figure out a way to make a link to this document on the agenda page (or to display it in some other way)

**Comment by gigamesh** [comment]
gotcha! I just hard coded that paragraph. I think that's the only method we've come up with for anything with embedded html (could be wrong - Mickey might have found a solution). 
I also added a button in the header to the same PDF. Feel free to approve & merge. :D

**Comment by doctor-gonzo** [comment]
thank you Matt!

**Pull request merged**
